[package]
name = "bob"
version = "0.1.0"
edition = "2024"

[features]
default   = ['fs', 'rev_proxy']
fs        = ['dep:actix-utils', 'dep:actix-files', 'dep:derive_more', 'dep:percent-encoding']
rev_proxy = ['dep:awc', 'dep:humantime', 'dep:serde_urlencoded']

[dependencies]
actix-files = { version = "0.6.6", optional = true }
actix-service = "2.0.3"
actix-utils = { version = "3.0.1", optional = true }
actix-web = { version = "4.11.0", features = ["rustls-0_23"] }
anyhow = "1.0.98"
awc = { version = "3.7.0", features = ["rustls-0_23", "rustls-0_23-native-roots", "rustls-0_23-webpki-roots"], optional = true }
clap = { version = "4.5.40", features = ["derive"] }
derive_more = { version = "2.0.1", optional = true, features = ["display"] }
env_logger = "0.11.8"
futures-core = "0.3.31"
glob = "0.3.2"
humantime = { version = "2.2.0", optional = true }
log = "0.4.27"
percent-encoding = { version =  "2.3.1", optional = true }
rustls = "0.23.28"
serde = { version = "1.0.219", features = ["derive"] }
serde_urlencoded = { version = "0.7.1", optional = true }
serde_yaml = "0.9.34"
