[workspace]
resolver = "3"
members = ["bob", "bob-cli"]

[profile.release]
codegen-units = 1
lto = true
panic = "abort"

[profile.dev.build-override]
opt-level = 0
codegen-units = 256
debug = false # when possible

[profile.release.build-override]
opt-level = 0
codegen-units = 256
